# Generated by Django 3.1.6 on 2021-02-15 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 13, 47, 8, 240507)),
        ),
        migrations.AddField(
            model_name='list',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2021, 2, 25, 13, 47, 8, 240507)),
        ),
        migrations.AlterField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
