# Generated by Django 3.1.6 on 2021-02-15 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20210215_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=True)),
                ('created_time', models.DateField(default=datetime.datetime(2021, 2, 15, 18, 0, 47, 891334))),
                ('end_time', models.DateField(default=datetime.datetime(2021, 2, 25, 18, 0, 47, 891334))),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
