# Generated by Django 3.1.6 on 2021-02-15 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20210215_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='list',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
