# Generated by Django 3.1.6 on 2021-02-15 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20210215_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
