# Generated by Django 3.1.6 on 2021-02-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_auto_20210215_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
